create table public.titanic (
  name text null,
  gender public.gender not null default 'male'::gender,
  age text null,
  class public.fareclass null,
  embarked text null,
  country text null,
  fare text null,
  survived public.survived not null default 'yes'::survived,
  id bigint generated by default as identity not null,
  constraint titanic_pkey primary key (id)
) TABLESPACE pg_default;                            